version: '3.8'

services:
  postgres:
    container_name: codeit_postgres
    image: postgres:13-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - db_network

  api:
    container_name: codeit_api
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    env_file:
      - .env
    networks:
      - db_network

volumes:
  postgres:

networks:
  db_network:
